# Generated by Django 5.0.7 on 2024-07-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_manager_img_alter_manager_company_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='img',
            field=models.ImageField(default='media/images/customer.png', upload_to='media/images'),
        ),
    ]
