# Generated by Django 5.0.7 on 2024-07-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_customer_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='img',
            field=models.ImageField(default='media/customer.png', upload_to='media'),
        ),
    ]
