# Generated by Django 5.0.7 on 2024-08-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_allmedia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allmedia',
            old_name='user',
            new_name='userid',
        ),
    ]
