# Generated by Django 5.0.7 on 2024-08-27 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_user_allmedia_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmedia',
            name='videofile',
            field=models.FileField(blank=True, null=True, upload_to='media/videos', verbose_name=''),
        ),
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_catagory', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_persons', models.CharField(max_length=10)),
                ('event_conformation_status', models.CharField(default='pending', max_length=15)),
                ('expected_price', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=10, null=True)),
                ('customer_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('manager_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manager')),
            ],
        ),
    ]
