# Generated by Django 5.0.7 on 2024-09-11 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_user_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(blank=True, max_length=30, null=True)),
                ('discription', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('manager_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manager')),
            ],
        ),
    ]
